Next_student_grading_1.py
massarinb/doppio-camp pull request #58
Opened 2021-06-14 10:37 UTC by nextdoppio

2021-06-15 03:50 UTC, nextdoppio commented
![Screenshot (81)](https://user-images.githubusercontent.com/85679340/121990127-77fa2400-cdc7-11eb-9918-590f4db21f2f.png)

2021-06-15 04:00 UTC, nextdoppio commented
![Screenshot (84)](https://user-images.githubusercontent.com/85679340/121990942-dffd3a00-cdc8-11eb-830d-6dabe66bf3f2.png)

2021-06-15 04:04 UTC, doppio-cds requested changes

2021-06-15 04:04 UTC, doppio-cds commented on testcases/camp4/Python/Next_student_grading_1.py
> +x = 49
ลบไฟล์นี้ค่ะ ไม่ save ใน path นี้ค่ะ

2021-06-15 04:10 UTC, nextdoppio commented on testcases/camp4/Python/Next_student_grading_1.py
> +x = 49
ลบแล้วครับ อันนี้ อันแรก ผมเซฟไฟล์ผิดครับ 55 
อันใหม่เซฟ ใน python / camp 4 แล้วครับ

2021-06-16 10:10 UTC, nextdoppio commented
![Screenshot (91)](https://user-images.githubusercontent.com/85679340/122200781-8d557800-cec5-11eb-85b0-c18f5bb85914.png)    NEXT_student_grading_2.py Python assignment 2 ครับ

2022-03-16 10:37 UTC, closed without merging